export { applyCareAction } from "./care/apply.js"
export { applyTrainingAction } from "./training/apply.js"
export { enterCompetition } from "./competition/enter.js"
export { runCompetition } from "./competition/run.js"
export { checkCompetitions } from "./competition/auto.js"
export { advanceAnimalAging } from "./animal/aging.js"
