/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminTreatmentsRouteImport } from './routes/_authenticated/admin/treatments'
import { Route as AuthenticatedAdminTrainingActionsRouteImport } from './routes/_authenticated/admin/training-actions'
import { Route as AuthenticatedAdminStatsRouteImport } from './routes/_authenticated/admin/stats'
import { Route as AuthenticatedAdminStageActivitiesRouteImport } from './routes/_authenticated/admin/stage-activities'
import { Route as AuthenticatedAdminSpeciesRouteImport } from './routes/_authenticated/admin/species'
import { Route as AuthenticatedAdminPersonalityTraitsRouteImport } from './routes/_authenticated/admin/personality-traits'
import { Route as AuthenticatedAdminLociRouteImport } from './routes/_authenticated/admin/loci'
import { Route as AuthenticatedAdminLifeStagesRouteImport } from './routes/_authenticated/admin/life-stages'
import { Route as AuthenticatedAdminIntensityTiersRouteImport } from './routes/_authenticated/admin/intensity-tiers'
import { Route as AuthenticatedAdminHealthConditionsRouteImport } from './routes/_authenticated/admin/health-conditions'
import { Route as AuthenticatedAdminHealthCertificatesRouteImport } from './routes/_authenticated/admin/health-certificates'
import { Route as AuthenticatedAdminGeneticPanelsRouteImport } from './routes/_authenticated/admin/genetic-panels'
import { Route as AuthenticatedAdminGameConfigRouteImport } from './routes/_authenticated/admin/game-config'
import { Route as AuthenticatedAdminExpressionRulesRouteImport } from './routes/_authenticated/admin/expression-rules'
import { Route as AuthenticatedAdminCareActionsRouteImport } from './routes/_authenticated/admin/care-actions'
import { Route as AuthenticatedAdminBreedsRouteImport } from './routes/_authenticated/admin/breeds'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTreatmentsRoute =
  AuthenticatedAdminTreatmentsRouteImport.update({
    id: '/treatments',
    path: '/treatments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTrainingActionsRoute =
  AuthenticatedAdminTrainingActionsRouteImport.update({
    id: '/training-actions',
    path: '/training-actions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStatsRoute = AuthenticatedAdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStageActivitiesRoute =
  AuthenticatedAdminStageActivitiesRouteImport.update({
    id: '/stage-activities',
    path: '/stage-activities',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSpeciesRoute =
  AuthenticatedAdminSpeciesRouteImport.update({
    id: '/species',
    path: '/species',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPersonalityTraitsRoute =
  AuthenticatedAdminPersonalityTraitsRouteImport.update({
    id: '/personality-traits',
    path: '/personality-traits',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLociRoute = AuthenticatedAdminLociRouteImport.update({
  id: '/loci',
  path: '/loci',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLifeStagesRoute =
  AuthenticatedAdminLifeStagesRouteImport.update({
    id: '/life-stages',
    path: '/life-stages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIntensityTiersRoute =
  AuthenticatedAdminIntensityTiersRouteImport.update({
    id: '/intensity-tiers',
    path: '/intensity-tiers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHealthConditionsRoute =
  AuthenticatedAdminHealthConditionsRouteImport.update({
    id: '/health-conditions',
    path: '/health-conditions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHealthCertificatesRoute =
  AuthenticatedAdminHealthCertificatesRouteImport.update({
    id: '/health-certificates',
    path: '/health-certificates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGeneticPanelsRoute =
  AuthenticatedAdminGeneticPanelsRouteImport.update({
    id: '/genetic-panels',
    path: '/genetic-panels',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGameConfigRoute =
  AuthenticatedAdminGameConfigRouteImport.update({
    id: '/game-config',
    path: '/game-config',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExpressionRulesRoute =
  AuthenticatedAdminExpressionRulesRouteImport.update({
    id: '/expression-rules',
    path: '/expression-rules',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCareActionsRoute =
  AuthenticatedAdminCareActionsRouteImport.update({
    id: '/care-actions',
    path: '/care-actions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBreedsRoute =
  AuthenticatedAdminBreedsRouteImport.update({
    id: '/breeds',
    path: '/breeds',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/breeds': typeof AuthenticatedAdminBreedsRoute
  '/admin/care-actions': typeof AuthenticatedAdminCareActionsRoute
  '/admin/expression-rules': typeof AuthenticatedAdminExpressionRulesRoute
  '/admin/game-config': typeof AuthenticatedAdminGameConfigRoute
  '/admin/genetic-panels': typeof AuthenticatedAdminGeneticPanelsRoute
  '/admin/health-certificates': typeof AuthenticatedAdminHealthCertificatesRoute
  '/admin/health-conditions': typeof AuthenticatedAdminHealthConditionsRoute
  '/admin/intensity-tiers': typeof AuthenticatedAdminIntensityTiersRoute
  '/admin/life-stages': typeof AuthenticatedAdminLifeStagesRoute
  '/admin/loci': typeof AuthenticatedAdminLociRoute
  '/admin/personality-traits': typeof AuthenticatedAdminPersonalityTraitsRoute
  '/admin/species': typeof AuthenticatedAdminSpeciesRoute
  '/admin/stage-activities': typeof AuthenticatedAdminStageActivitiesRoute
  '/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/admin/training-actions': typeof AuthenticatedAdminTrainingActionsRoute
  '/admin/treatments': typeof AuthenticatedAdminTreatmentsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/breeds': typeof AuthenticatedAdminBreedsRoute
  '/admin/care-actions': typeof AuthenticatedAdminCareActionsRoute
  '/admin/expression-rules': typeof AuthenticatedAdminExpressionRulesRoute
  '/admin/game-config': typeof AuthenticatedAdminGameConfigRoute
  '/admin/genetic-panels': typeof AuthenticatedAdminGeneticPanelsRoute
  '/admin/health-certificates': typeof AuthenticatedAdminHealthCertificatesRoute
  '/admin/health-conditions': typeof AuthenticatedAdminHealthConditionsRoute
  '/admin/intensity-tiers': typeof AuthenticatedAdminIntensityTiersRoute
  '/admin/life-stages': typeof AuthenticatedAdminLifeStagesRoute
  '/admin/loci': typeof AuthenticatedAdminLociRoute
  '/admin/personality-traits': typeof AuthenticatedAdminPersonalityTraitsRoute
  '/admin/species': typeof AuthenticatedAdminSpeciesRoute
  '/admin/stage-activities': typeof AuthenticatedAdminStageActivitiesRoute
  '/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/admin/training-actions': typeof AuthenticatedAdminTrainingActionsRoute
  '/admin/treatments': typeof AuthenticatedAdminTreatmentsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/breeds': typeof AuthenticatedAdminBreedsRoute
  '/_authenticated/admin/care-actions': typeof AuthenticatedAdminCareActionsRoute
  '/_authenticated/admin/expression-rules': typeof AuthenticatedAdminExpressionRulesRoute
  '/_authenticated/admin/game-config': typeof AuthenticatedAdminGameConfigRoute
  '/_authenticated/admin/genetic-panels': typeof AuthenticatedAdminGeneticPanelsRoute
  '/_authenticated/admin/health-certificates': typeof AuthenticatedAdminHealthCertificatesRoute
  '/_authenticated/admin/health-conditions': typeof AuthenticatedAdminHealthConditionsRoute
  '/_authenticated/admin/intensity-tiers': typeof AuthenticatedAdminIntensityTiersRoute
  '/_authenticated/admin/life-stages': typeof AuthenticatedAdminLifeStagesRoute
  '/_authenticated/admin/loci': typeof AuthenticatedAdminLociRoute
  '/_authenticated/admin/personality-traits': typeof AuthenticatedAdminPersonalityTraitsRoute
  '/_authenticated/admin/species': typeof AuthenticatedAdminSpeciesRoute
  '/_authenticated/admin/stage-activities': typeof AuthenticatedAdminStageActivitiesRoute
  '/_authenticated/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/_authenticated/admin/training-actions': typeof AuthenticatedAdminTrainingActionsRoute
  '/_authenticated/admin/treatments': typeof AuthenticatedAdminTreatmentsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/admin/breeds'
    | '/admin/care-actions'
    | '/admin/expression-rules'
    | '/admin/game-config'
    | '/admin/genetic-panels'
    | '/admin/health-certificates'
    | '/admin/health-conditions'
    | '/admin/intensity-tiers'
    | '/admin/life-stages'
    | '/admin/loci'
    | '/admin/personality-traits'
    | '/admin/species'
    | '/admin/stage-activities'
    | '/admin/stats'
    | '/admin/training-actions'
    | '/admin/treatments'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/'
    | '/admin/breeds'
    | '/admin/care-actions'
    | '/admin/expression-rules'
    | '/admin/game-config'
    | '/admin/genetic-panels'
    | '/admin/health-certificates'
    | '/admin/health-conditions'
    | '/admin/intensity-tiers'
    | '/admin/life-stages'
    | '/admin/loci'
    | '/admin/personality-traits'
    | '/admin/species'
    | '/admin/stage-activities'
    | '/admin/stats'
    | '/admin/training-actions'
    | '/admin/treatments'
    | '/admin'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/'
    | '/_authenticated/admin/breeds'
    | '/_authenticated/admin/care-actions'
    | '/_authenticated/admin/expression-rules'
    | '/_authenticated/admin/game-config'
    | '/_authenticated/admin/genetic-panels'
    | '/_authenticated/admin/health-certificates'
    | '/_authenticated/admin/health-conditions'
    | '/_authenticated/admin/intensity-tiers'
    | '/_authenticated/admin/life-stages'
    | '/_authenticated/admin/loci'
    | '/_authenticated/admin/personality-traits'
    | '/_authenticated/admin/species'
    | '/_authenticated/admin/stage-activities'
    | '/_authenticated/admin/stats'
    | '/_authenticated/admin/training-actions'
    | '/_authenticated/admin/treatments'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/treatments': {
      id: '/_authenticated/admin/treatments'
      path: '/treatments'
      fullPath: '/admin/treatments'
      preLoaderRoute: typeof AuthenticatedAdminTreatmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/training-actions': {
      id: '/_authenticated/admin/training-actions'
      path: '/training-actions'
      fullPath: '/admin/training-actions'
      preLoaderRoute: typeof AuthenticatedAdminTrainingActionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/stats': {
      id: '/_authenticated/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AuthenticatedAdminStatsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/stage-activities': {
      id: '/_authenticated/admin/stage-activities'
      path: '/stage-activities'
      fullPath: '/admin/stage-activities'
      preLoaderRoute: typeof AuthenticatedAdminStageActivitiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/species': {
      id: '/_authenticated/admin/species'
      path: '/species'
      fullPath: '/admin/species'
      preLoaderRoute: typeof AuthenticatedAdminSpeciesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/personality-traits': {
      id: '/_authenticated/admin/personality-traits'
      path: '/personality-traits'
      fullPath: '/admin/personality-traits'
      preLoaderRoute: typeof AuthenticatedAdminPersonalityTraitsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/loci': {
      id: '/_authenticated/admin/loci'
      path: '/loci'
      fullPath: '/admin/loci'
      preLoaderRoute: typeof AuthenticatedAdminLociRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/life-stages': {
      id: '/_authenticated/admin/life-stages'
      path: '/life-stages'
      fullPath: '/admin/life-stages'
      preLoaderRoute: typeof AuthenticatedAdminLifeStagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/intensity-tiers': {
      id: '/_authenticated/admin/intensity-tiers'
      path: '/intensity-tiers'
      fullPath: '/admin/intensity-tiers'
      preLoaderRoute: typeof AuthenticatedAdminIntensityTiersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/health-conditions': {
      id: '/_authenticated/admin/health-conditions'
      path: '/health-conditions'
      fullPath: '/admin/health-conditions'
      preLoaderRoute: typeof AuthenticatedAdminHealthConditionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/health-certificates': {
      id: '/_authenticated/admin/health-certificates'
      path: '/health-certificates'
      fullPath: '/admin/health-certificates'
      preLoaderRoute: typeof AuthenticatedAdminHealthCertificatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/genetic-panels': {
      id: '/_authenticated/admin/genetic-panels'
      path: '/genetic-panels'
      fullPath: '/admin/genetic-panels'
      preLoaderRoute: typeof AuthenticatedAdminGeneticPanelsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/game-config': {
      id: '/_authenticated/admin/game-config'
      path: '/game-config'
      fullPath: '/admin/game-config'
      preLoaderRoute: typeof AuthenticatedAdminGameConfigRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/expression-rules': {
      id: '/_authenticated/admin/expression-rules'
      path: '/expression-rules'
      fullPath: '/admin/expression-rules'
      preLoaderRoute: typeof AuthenticatedAdminExpressionRulesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/care-actions': {
      id: '/_authenticated/admin/care-actions'
      path: '/care-actions'
      fullPath: '/admin/care-actions'
      preLoaderRoute: typeof AuthenticatedAdminCareActionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/breeds': {
      id: '/_authenticated/admin/breeds'
      path: '/breeds'
      fullPath: '/admin/breeds'
      preLoaderRoute: typeof AuthenticatedAdminBreedsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBreedsRoute: typeof AuthenticatedAdminBreedsRoute
  AuthenticatedAdminCareActionsRoute: typeof AuthenticatedAdminCareActionsRoute
  AuthenticatedAdminExpressionRulesRoute: typeof AuthenticatedAdminExpressionRulesRoute
  AuthenticatedAdminGameConfigRoute: typeof AuthenticatedAdminGameConfigRoute
  AuthenticatedAdminGeneticPanelsRoute: typeof AuthenticatedAdminGeneticPanelsRoute
  AuthenticatedAdminHealthCertificatesRoute: typeof AuthenticatedAdminHealthCertificatesRoute
  AuthenticatedAdminHealthConditionsRoute: typeof AuthenticatedAdminHealthConditionsRoute
  AuthenticatedAdminIntensityTiersRoute: typeof AuthenticatedAdminIntensityTiersRoute
  AuthenticatedAdminLifeStagesRoute: typeof AuthenticatedAdminLifeStagesRoute
  AuthenticatedAdminLociRoute: typeof AuthenticatedAdminLociRoute
  AuthenticatedAdminPersonalityTraitsRoute: typeof AuthenticatedAdminPersonalityTraitsRoute
  AuthenticatedAdminSpeciesRoute: typeof AuthenticatedAdminSpeciesRoute
  AuthenticatedAdminStageActivitiesRoute: typeof AuthenticatedAdminStageActivitiesRoute
  AuthenticatedAdminStatsRoute: typeof AuthenticatedAdminStatsRoute
  AuthenticatedAdminTrainingActionsRoute: typeof AuthenticatedAdminTrainingActionsRoute
  AuthenticatedAdminTreatmentsRoute: typeof AuthenticatedAdminTreatmentsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBreedsRoute: AuthenticatedAdminBreedsRoute,
  AuthenticatedAdminCareActionsRoute: AuthenticatedAdminCareActionsRoute,
  AuthenticatedAdminExpressionRulesRoute:
    AuthenticatedAdminExpressionRulesRoute,
  AuthenticatedAdminGameConfigRoute: AuthenticatedAdminGameConfigRoute,
  AuthenticatedAdminGeneticPanelsRoute: AuthenticatedAdminGeneticPanelsRoute,
  AuthenticatedAdminHealthCertificatesRoute:
    AuthenticatedAdminHealthCertificatesRoute,
  AuthenticatedAdminHealthConditionsRoute:
    AuthenticatedAdminHealthConditionsRoute,
  AuthenticatedAdminIntensityTiersRoute: AuthenticatedAdminIntensityTiersRoute,
  AuthenticatedAdminLifeStagesRoute: AuthenticatedAdminLifeStagesRoute,
  AuthenticatedAdminLociRoute: AuthenticatedAdminLociRoute,
  AuthenticatedAdminPersonalityTraitsRoute:
    AuthenticatedAdminPersonalityTraitsRoute,
  AuthenticatedAdminSpeciesRoute: AuthenticatedAdminSpeciesRoute,
  AuthenticatedAdminStageActivitiesRoute:
    AuthenticatedAdminStageActivitiesRoute,
  AuthenticatedAdminStatsRoute: AuthenticatedAdminStatsRoute,
  AuthenticatedAdminTrainingActionsRoute:
    AuthenticatedAdminTrainingActionsRoute,
  AuthenticatedAdminTreatmentsRoute: AuthenticatedAdminTreatmentsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
