-- AlterTable
ALTER TABLE "Breed" ADD COLUMN     "immunityMax" DOUBLE PRECISION,
ADD COLUMN     "immunityMin" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "GameConfig" ADD COLUMN     "cyclesPerYear" INTEGER NOT NULL DEFAULT 12,
ADD COLUMN     "immunityMax" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN     "immunityMin" DOUBLE PRECISION NOT NULL DEFAULT 0;
